/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import dao.DAO_Phong;
import entity.Phong;
import helper.BLL_Phong;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tamnt
 */
public class QuanLyPhongJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyPhongJDialog
     */
    public QuanLyPhongJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        form = this;
//        BLL.BLL_Phong.DoDuLieuBang(tbl_Phong);
        BLL_Phong.Load_cbbTang(cboTang);
        rdoChonTang.setSelected(true);
        LuaChon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDienTich = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdoChonTang = new javax.swing.JRadioButton();
        cboTang = new javax.swing.JComboBox<>();
        rdoNhapTang = new javax.swing.JRadioButton();
        txtNhapTang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiuongDon = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtGiuongDoi = new javax.swing.JTextField();
        btnCong2 = new javax.swing.JButton();
        btnTru2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblAnh2 = new javax.swing.JLabel();
        btnXoaAnh = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhong = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Phòng");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        tab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã Phòng :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 20, 70, 15);
        jPanel2.add(txtMaPhong);
        txtMaPhong.setBounds(170, 10, 240, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Loại Phòng :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 70, 73, 15);

        cboLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboLoaiPhong);
        cboLoaiPhong.setBounds(170, 60, 240, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Diện Tích :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 120, 70, 15);

        txtDienTich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDienTichKeyReleased(evt);
            }
        });
        jPanel2.add(txtDienTich);
        txtDienTich.setBounds(170, 110, 240, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tầng :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 170, 40, 15);

        buttonGroup1.add(rdoChonTang);
        rdoChonTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChonTangActionPerformed(evt);
            }
        });
        jPanel2.add(rdoChonTang);
        rdoChonTang.setBounds(170, 160, 30, 30);

        cboTang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboTang);
        cboTang.setBounds(210, 160, 200, 30);

        buttonGroup1.add(rdoNhapTang);
        rdoNhapTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNhapTangActionPerformed(evt);
            }
        });
        jPanel2.add(rdoNhapTang);
        rdoNhapTang.setBounds(170, 200, 30, 30);

        txtNhapTang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNhapTangKeyReleased(evt);
            }
        });
        jPanel2.add(txtNhapTang);
        txtNhapTang.setBounds(210, 200, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Số Giường Đơn :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 260, 100, 15);

        txtGiuongDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiuongDonKeyReleased(evt);
            }
        });
        jPanel2.add(txtGiuongDon);
        txtGiuongDon.setBounds(170, 250, 140, 30);

        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });
        jPanel2.add(btnCong);
        btnCong.setBounds(320, 250, 22, 30);

        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });
        jPanel2.add(btnTru);
        btnTru.setBounds(370, 250, 40, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Số Giường Đôi :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 310, 100, 15);

        txtGiuongDoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiuongDoiKeyReleased(evt);
            }
        });
        jPanel2.add(txtGiuongDoi);
        txtGiuongDoi.setBounds(170, 300, 140, 30);

        btnCong2.setText("+");
        btnCong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCong2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCong2);
        btnCong2.setBounds(320, 303, 22, 30);

        btnTru2.setText("-");
        btnTru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTru2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnTru2);
        btnTru2.setBounds(370, 303, 40, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnh2.setBackground(new java.awt.Color(255, 255, 255));
        lblAnh2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnh2MouseClicked(evt);
            }
        });
        jPanel3.add(lblAnh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 180, 200));

        btnXoaAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resort/icon/Delete.png"))); // NOI18N
        btnXoaAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaAnhActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoaAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Hình");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel3);
        jPanel3.setBounds(30, 350, 180, 240);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Ghi Chú");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(230, 350, 50, 15);

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(230, 370, 190, 220);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Loại Phòng", "Diện Tích", "Hình", "Tình Trạng", "Tầng"
            }
        ));
        tblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhong);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(450, 10, 720, 630);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resort/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem);
        btnThem.setBounds(40, 600, 90, 40);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resort/icon/Trash.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);
        btnXoa.setBounds(140, 600, 80, 40);

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resort/icon/Upload.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua);
        btnSua.setBounds(230, 600, 90, 40);

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resort/icon/Sync.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel2.add(btnMoi);
        btnMoi.setBounds(330, 600, 90, 40);

        tab.addTab("PHÒNG", jPanel2);

        jPanel1.add(tab, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        GanThongTin();
        if (BLL_Phong.Them(P)) {
            DAO_Phong.ThemPhong(P);
            BLL_Phong.DoDuLieuBang(tblPhong);
            save_IMG(f);
            BLL_Phong.Load_cbbTang(cboTang);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaAnhActionPerformed
        // TODO add your handling code here:
        imageName = null;
        lblAnh2.setIcon(null);
    }//GEN-LAST:event_btnXoaAnhActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        BLL_Phong.DoDuLieuBang(tblPhong);
        BLL_Phong.loadData_LoaiPhong(cboLoaiPhong);
//        LoaiPhongJDialog pnl = new LoaiPhongJDialog();
//        tab.add("Loại phòng", pnl);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void lblAnh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnh2MouseClicked
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int resuft = file.showOpenDialog(null);
        if (resuft == JFileChooser.APPROVE_OPTION) {
            f = file.getSelectedFile();
            imageName = f.getAbsolutePath();
            ImageIcon ii = new ImageIcon(new ImageIcon(imageName).getImage().getScaledInstance(lblAnh2.getWidth(), lblAnh2.getHeight(), Image.SCALE_SMOOTH));
            lblAnh2.setIcon(ii);
            imageName = f.getName();
        }
    }//GEN-LAST:event_lblAnh2MouseClicked

    private void tblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongMouseClicked
        // TODO add your handling code here:
        if (tblPhong.getSelectedRowCount() == 1) {
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
            txtMaPhong.setFocusable(false);
            int vitri = tblPhong.getSelectedRow();
            String MaPhong = tblPhong.getValueAt(vitri, 0).toString();
            DienTTVaoTextField(MaPhong);

        }
    }//GEN-LAST:event_tblPhongMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "bạn chắc chắn xóa?", "xóA", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tblPhong.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                String MaPhong = tblPhong.getValueAt(cacdong[i], 0).toString();
                if (BLL_Phong.KT_Xoa(MaPhong)) {
                    DAO_Phong.Xoa(MaPhong);
                    LamMoi();
                }

            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        LamMoi();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        GanThongTin();
        if (BLL_Phong.KT_Sua(P)) {
            DAO_Phong.Sua(P);
            save_IMG(f);
            BLL_Phong.Load_cbbTang(cboTang);
            LamMoi();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtDienTichKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDienTichKeyReleased
        // TODO add your handling code here:
        try {
            int sl = Integer.parseInt(txtDienTich.getText());

        } catch (Exception e) {
            txtDienTich.setText("0");
        }
    }//GEN-LAST:event_txtDienTichKeyReleased

    private void rdoChonTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChonTangActionPerformed
        // TODO add your handling code here:
        LuaChon();
    }//GEN-LAST:event_rdoChonTangActionPerformed

    private void rdoNhapTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNhapTangActionPerformed
        // TODO add your handling code here:
        LuaChon();
    }//GEN-LAST:event_rdoNhapTangActionPerformed

    private void txtNhapTangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhapTangKeyReleased
        // TODO add your handling code here:
        try {
            int sl = Integer.parseInt(txtNhapTang.getText());

        } catch (Exception e) {
            txtNhapTang.setText("0");

        }
    }//GEN-LAST:event_txtNhapTangKeyReleased

    private void txtGiuongDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiuongDonKeyReleased
        // TODO add your handling code here:
        try {
            int sl = Integer.parseInt(txtGiuongDon.getText());

        } catch (Exception e) {
            txtGiuongDon.setText("0");

        }
    }//GEN-LAST:event_txtGiuongDonKeyReleased

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        // TODO add your handling code here:
        if (!txtGiuongDon.getText().equals("0")) {
            SoLuongGiuongDon(-1);

        }
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        SoLuongGiuongDon(1);
    }//GEN-LAST:event_btnCongActionPerformed

    private void txtGiuongDoiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiuongDoiKeyReleased
        // TODO add your handling code here:
        try {
            int sl = Integer.parseInt(txtGiuongDoi.getText());

        } catch (Exception e) {
            txtGiuongDoi.setText("0");

        }
    }//GEN-LAST:event_txtGiuongDoiKeyReleased

    private void btnTru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTru2ActionPerformed
        // TODO add your handling code here:
        if (!txtGiuongDoi.getText().equals("0")) {
            SoLuongGiuongDoi(-1);

        }
    }//GEN-LAST:event_btnTru2ActionPerformed

    private void btnCong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCong2ActionPerformed
        // TODO add your handling code here:
        SoLuongGiuongDoi(1);
    }//GEN-LAST:event_btnCong2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyPhongJDialog dialog = new QuanLyPhongJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnCong2;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btnTru2;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaAnh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboLoaiPhong;
    private javax.swing.JComboBox<String> cboTang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnh2;
    private javax.swing.JRadioButton rdoChonTang;
    private javax.swing.JRadioButton rdoNhapTang;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tblPhong;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiuongDoi;
    private javax.swing.JTextField txtGiuongDon;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtNhapTang;
    // End of variables declaration//GEN-END:variables

    int x, y;
    File f;
    public static QuanLyPhongJDialog form;

    public static boolean save_IMG(File file) {
        File dir = new File("IMG_Phong");
        if (!dir.exists()) {
            dir.mkdirs();
        }

        try {
            File newfile = new File(dir, file.getName());
            Path source = Paths.get(file.getAbsolutePath());
            Path ok = Paths.get(newfile.getAbsolutePath());
            Files.copy(source, ok, StandardCopyOption.REPLACE_EXISTING);
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    public void lbl_ImageNV(String ImagePath) {
        ImageIcon icon = new ImageIcon("IMG_Phong\\" + ImagePath);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(lblAnh2.getWidth(), lblAnh2.getHeight(), image.SCALE_SMOOTH));
        lblAnh2.setIcon(icon1);
    }

    public static Phong P = new Phong();
    public static String imageName = null;

    private void LuaChon() {//lựa chọn tầng hay tự nhập tầng
        if (rdoChonTang.isSelected()) {
            txtNhapTang.setEnabled(false);
            cboTang.setEnabled(true);
        } else {
            cboTang.setEnabled(false);
            txtNhapTang.setEnabled(true);
        }
    }

    private void GanThongTin() {
        P.setMaPhong(txtMaPhong.getText());
        P.setDienTich(txtDienTich.getText());
        P.setGhiChu(txtGhiChu.getText());
        mycombobox mb = (mycombobox) cboLoaiPhong.getSelectedItem();
        P.setMaLoaiPhong(mb.value.toString());
        P.setGiuongDon(txtGiuongDon.getText());
        P.setGiuongDoi(txtGiuongDoi.getText());
        if (rdoChonTang.isSelected()) {
            P.setTang(cboTang.getSelectedItem().toString());
            System.out.println("tang " + P.getTang());
        } else {
            P.setTang(txtNhapTang.getText());
        }
//        System.out.println("loaiphong" + P.getMaLoaiPhong());
        P.setHinh(imageName);
    }

    private void DienTTVaoTextField(String MaPhong) {
        ResultSet rs = DAO_Phong.LayTheoMa(MaPhong);
        try {
            if (rs.next()) {
                txtMaPhong.setText(rs.getString("MaPhong"));
                txtDienTich.setText(String.valueOf(rs.getInt("DienTich")));
                txtGhiChu.setText(rs.getString("GhiChu"));
                imageName = rs.getString("Hinh");
//                ImageIcon ii = new ImageIcon(new ImageIcon(imageName).getImage().getScaledInstance(lbl_Anh2.getWidth(), lbl_Anh2.getHeight(), Image.SCALE_SMOOTH));
//                lbl_Anh2.setIcon(ii);
                lbl_ImageNV(imageName);
                String MaLoaiPhong = rs.getString("MaLoaiPhong");
                DefaultComboBoxModel cbbModel = (DefaultComboBoxModel) cboLoaiPhong.getModel();
                for (int i = 0; i < cboLoaiPhong.getItemCount(); i++) {
                    mycombobox mb = (mycombobox) cbbModel.getElementAt(i);
                    if (MaLoaiPhong.equals(mb.value)) {
                        txtNhapTang.setEnabled(false);
                        rdoChonTang.setSelected(true);
                        cboTang.setEnabled(true);
                        cboLoaiPhong.setSelectedIndex(i);
                    } else {
                    }
                }
                for (int i = 0; i < cboTang.getItemCount(); i++) {
                    if (rs.getString("MaTang").matches(cboTang.getItemAt(i))) {
                        cboTang.setSelectedIndex(i);
                    } else {

                    }
                }
                txtGiuongDon.setText(rs.getString("GiuongDon"));
                txtGiuongDoi.setText(rs.getString("GiuongDoi"));
            }
        } catch (SQLException ex) {
            System.out.println("kaka loi roi");
        }
    }

    private void LamMoi() {
        BLL_Phong.DoDuLieuBang(tblPhong);
        BLL_Phong.loadData_LoaiPhong(cboLoaiPhong);
        txtMaPhong.setText("");
        txtDienTich.setText("");
        txtGhiChu.setText("");
        txtMaPhong.setFocusable(true);
        imageName = null;
        lblAnh2.setIcon(null);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }

    private void SoLuongGiuongDon(int giatri) {
        int sl = Integer.parseInt(txtGiuongDon.getText());
        sl = sl + (giatri);
        txtGiuongDon.setText(String.valueOf(sl));
    }

    private void SoLuongGiuongDoi(int giatri) {
        int sl = Integer.parseInt(txtGiuongDoi.getText());
        sl = sl + (giatri);
        txtGiuongDoi.setText(String.valueOf(sl));
    }
}
